// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS0E-iRR90c9lDXXQScsW-DocmdkjFe1k',
    appId: '1:390033949861:web:f449e50e2d8458ea42b94c',
    messagingSenderId: '390033949861',
    projectId: 'pate-2fcda',
    authDomain: 'pate-2fcda.firebaseapp.com',
    storageBucket: 'pate-2fcda.appspot.com',
    measurementId: 'G-6YMX27RQJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4wiw9Fa0z7Fnfee9sgYslwAOX8TtNBz0',
    appId: '1:390033949861:android:8530c86d3738b1e842b94c',
    messagingSenderId: '390033949861',
    projectId: 'pate-2fcda',
    storageBucket: 'pate-2fcda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFNbGD3k3Wi-WG-_6pLX3AR6A6THkL0q0',
    appId: '1:390033949861:ios:737e09e656c7f08542b94c',
    messagingSenderId: '390033949861',
    projectId: 'pate-2fcda',
    storageBucket: 'pate-2fcda.appspot.com',
    iosClientId: '390033949861-bj1o0vae8legj6s68gvmgmp2gg06plro.apps.googleusercontent.com',
    iosBundleId: 'com.example.pate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFNbGD3k3Wi-WG-_6pLX3AR6A6THkL0q0',
    appId: '1:390033949861:ios:737e09e656c7f08542b94c',
    messagingSenderId: '390033949861',
    projectId: 'pate-2fcda',
    storageBucket: 'pate-2fcda.appspot.com',
    iosClientId: '390033949861-bj1o0vae8legj6s68gvmgmp2gg06plro.apps.googleusercontent.com',
    iosBundleId: 'com.example.pate',
  );
}
